# Generated by Django 3.2.2 on 2023-11-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email_field', models.BooleanField(default=False)),
                ('phone_field', models.BooleanField(default=False)),
                ('date_field', models.BooleanField(default=False)),
                ('text_field', models.BooleanField(default=False)),
            ],
        ),
    ]
