# Generated by Django 3.2.2 on 2023-11-14 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_validator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formtemplate',
            old_name='date_field',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='formtemplate',
            old_name='email_field',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='formtemplate',
            old_name='phone_field',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='formtemplate',
            old_name='text_field',
            new_name='text',
        ),
    ]
