# Generated by Django 3.2.3 on 2023-11-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.BooleanField(default=False)),
                ('phone', models.BooleanField(default=False)),
                ('date', models.BooleanField(default=False)),
                ('text', models.BooleanField(default=False)),
            ],
        ),
    ]
